#!/bin/bash

if [[ \$USER == "root" || $(whoami) == "root" ]]; then
  echo "Error: Do not run this as root"
  exit
fi

echo "Installing webb ..."
curl https://codeload.github.com/Rohan62442/Webb/zip/master -o Webb.zip
unzip -q Webb.zip
cd Webb-master
chmod +x webb.installer
./webb.installer

cd ..
rm -rf Webb-master Webb.zip
echo "webb was installed successfully."
