#!/usr/bin/env python3
#
# Webb helps you manage web applications on GNOME's Epiphany browser.
# You can install, remove or create brand new applications all from
# the comfort of your Terminal.
#
# Copyright (C) 2015 Rohan Pinto
#
# License: GNU GPLv3 <http://www.gnu.org/licenses/gpl-3.0.html>
# Author: Rohan Pinto <rohan62442@hotmail.com>
# Code: GitHub <https://github.com/Rohan62442/Webb>

def check_args():
    args=sys.argv
    if len(args)==1:
        usage()
    elif len(args)==2 and (args[1]=="-h" or args[1]=="--help"):
        usage()
    elif len(args)==2 and args[1]=="-l":
        list_installed()
    elif len(args)==4 and args[1]=="-c":
        create_new(args[2], args[3])
    elif len(args)>2:
        if args[1]=="-l" and args[2]=="--all" and len(args)==3:
            list_all()
        elif args[1]=="-i" and args[2]=="--all" and len(args)==3:
            install_all()
        elif args[1]=="-r" and args[2]=="--all" and len(args)==3:
            remove_all()
        elif args[1]=="-i":
            for i in range(2,len(args)):
                install(args[i])
        elif args[1]=="-r":
            for i in range(2,len(args)):
                remove(args[i])
        else:
            print("webb: Invalid option\nTry 'webb --help' for more information.")
    else:
        print("webb: Invalid option\nTry 'webb --help' for more information.")

def usage():
    help_str="""Usage: webb [OPTION]...
Install or remove web applications for Epiphany

 Mandatory arguments
   --all,                   List, install or remove all available apps.
                            Used with '-l', '-i' and '-r'
   -h, --help               Print 'Usage' and exit
   -i <apps>                Install the specified app(s)
   -l,                      List installed or all apps
   -r <apps>                Remove the specified app(s)
   -c <app> <url>           Create & install a new app

 Copyright (C) 2015 Rohan Pinto"""
    print(help_str)

if __name__ == "__main__":
    import os, sys
    if os.geteuid()==0:
        sys.exit("Error: Do not run this script as root!")
    os.chdir('/usr/share/webb')
    from run.checking import *
    from run.listing import *
    from run.installing import *
    from run.removing import *
    from run.creating import *
    check_args()
